<?php

namespace Admin\BackBundle\Repository;

/**
 * PassportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassportRepository extends \Doctrine\ORM\EntityRepository
{
}
