admin_back:
    resource: "@AdminBackBundle/Controller/"
    type:     annotation
    prefix:   /

home_sing:
    resource: "@HomeSingBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
